export const SET_TODOS = 'SET_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TITLE_TODO = 'UPDATE_TITLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const CHANGE_STATUS_TODO = 'CHANGE_STATUS_TODO';
export const TOGGLE_STATUS_TODO = 'TOGGLE_STATUS_TODO';
export const CLEAR_ALL_COMPLETED_TODOS = 'CLEAR_ALL_COMPLETED_TODOS';
export const SET_FILTER_TYPE = 'SET_FILTER';
